post_install() {
  rm -f /etc/init.d/vga_check.sh

  systemctl preset loonggl-hack.service >/dev/null 2>&1 || true

  if ! systemd-detect-virt -q 2>/dev/null; then
    systemctl daemon-reload >/dev/null 2>&1 || true
    systemctl restart loonggl-hack.service >/dev/null 2>&1 || true
  fi
}

post_upgrade() {
  post_install
}

pre_remove() {
  rm -f /usr/share/glvnd/egl_vendor.d/40_{gs,loong}gpu.json
  rm -f /etc/init.d/vga_check.sh
}
